version: '3.8'

services:
  server:
    build: .
    container_name: server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - pgdb
      - rabbit
      - celery

  celery:
    build: .
    command: sh -c 'sleep 10; celery -A core worker -l INFO'
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    depends_on:
      - pgdb
      - rabbit

  pgdb:
    image: postgres
    container_name: db
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data/
    restart: on-failure

  rabbit:
    image: "rabbitmq:3-management-alpine"
    container_name: rabbit
    env_file:
      - .env
    ports:
    - "5672:5672"
    - "15672:15672"
    restart: on-failure

volumes:
  pgdata: {}