version: '3'

services:
  db:
    image: postgres:12.6
    container_name: db
    env_file:
      - .env
    ports:
    - '5432:5432'
    volumes:
    - data:/var/lib/postresql/data

volumes:
  data: {}
