# Generated by Django 3.1.7 on 2021-03-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210328_1742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.AddField(
            model_name='news',
            name='section',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
