# Generated by Django 3.1.7 on 2021-04-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210330_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='section',
            field=models.CharField(default='main', max_length=50),
        ),
    ]
